matrix:
  include:
    - language: bash

      addons:
        apt:
          sources:
          - debian-sid

      install:
        - sudo apt-get install -y shellcheck

      script:
        - bash -c 'find -name "*.sh" | xargs shellcheck -x -e SC2034,SC2148'


    - language: python

      python:
        - 3.6

      install:
        - pip install pylint==2.3.1

      script:
        - find -name "*.py" | xargs pylint
